project:
  type: website
  resources:
    - index.html
    - support.js
    - data.js
    - TdF-Tipprunde-LeTour.dc.html
    - TdF-Tipprunde-Nachtfahrt.dc.html

website:
  title: "TdF2026"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

